package com.aspire.ecoplate;

import android.os.Bundle;
import android.view.View;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.dialog.MaterialAlertDialogBuilder;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class RecipeActivity extends AppCompatActivity {

    private final ExecutorService executor = Executors.newSingleThreadExecutor();

    private DatabaseHelper db;
    private TextView tvUsing;
    private TextView tvSource;
    private TextView tvMessage;
    private View loading;
    private RecipeAdapter adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_recipes);
        Ui.edgeToEdge(this, findViewById(R.id.recipeRoot));

        MaterialToolbar toolbar = findViewById(R.id.toolbar);
        toolbar.setNavigationOnClickListener(v -> finish());

        db = new DatabaseHelper(this);

        tvUsing = findViewById(R.id.tvUsing);
        tvSource = findViewById(R.id.tvSource);
        tvMessage = findViewById(R.id.tvMessage);
        loading = findViewById(R.id.loading);

        adapter = new RecipeAdapter();
        adapter.setOnCookedClickListener(this::onRecipeCooked);
        RecyclerView rv = findViewById(R.id.rvRecipes);
        rv.setLayoutManager(new LinearLayoutManager(this));
        rv.setAdapter(adapter);

        List<String> ingredients = pickIngredients();
        if (ingredients.isEmpty()) {
            loading.setVisibility(View.GONE);
            tvUsing.setText("Nothing safe to cook with");
            tvMessage.setVisibility(View.VISIBLE);
            tvMessage.setText("Every item in your pantry has expired. Remove them and add fresh items to get recipe ideas.");
            return;
        }

        tvUsing.setText("Cooking with " + joinNames(ingredients));
        tvSource.setText("");
        loadRecipes(ingredients);
    }

    private List<String> pickIngredients() {
        List<PantryItem> all = db.getActive();
        List<String> names = new ArrayList<>();
        for (PantryItem item : all) {
            if (item.daysLeft() >= 0 && item.daysLeft() <= 7) {
                names.add(item.name);
            }
        }
        if (names.size() < 3) {
            for (PantryItem item : all) {
                if (item.daysLeft() > 7 && names.size() < 4) {
                    names.add(item.name);
                }
            }
        }
        return names.size() > 8 ? new ArrayList<>(names.subList(0, 8)) : names;
    }

    private String joinNames(List<String> names) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < names.size(); i++) {
            if (i > 0) sb.append(i == names.size() - 1 ? " and " : ", ");
            sb.append(names.get(i).toLowerCase());
        }
        return sb.toString();
    }

    private void loadRecipes(List<String> ingredients) {
        executor.execute(() -> {
            List<Recipe> result = null;
            String source = "";
            String inedibleWarning = null;

            try {
                if (!Config.isGroqConfigured()) {
                    throw new IllegalStateException("Groq API Key is missing from local.properties");
                }
                result = GroqClient.suggestRecipes(ingredients);
                source = "Generated by Groq AI";
            } catch (IllegalArgumentException e) {
                // Non-food / inedible item guardrail — extract warning, show no recipes
                inedibleWarning = e.getMessage() != null
                        ? e.getMessage()
                        : "Those items do not look like food! Please add valid pantry ingredients.";
            } catch (Exception e) {
                android.util.Log.e("EcoPlateError", "AI fetch failed", e);
                result = RecipeFallback.suggest(ingredients);
                source = "The AI service could not be reached, so these are offline suggestions.";
            }

            final List<Recipe> finalResult = result != null ? result : new ArrayList<>();
            final String finalSource = source;
            final String finalWarning = inedibleWarning;

            runOnUiThread(() -> {
                loading.setVisibility(View.GONE);

                if (finalWarning != null) {
                    // Inedible path: clear header, show warning, no recipes, no source text
                    tvUsing.setText("Invalid ingredients");
                    tvSource.setText("");
                    tvMessage.setVisibility(View.VISIBLE);
                    tvMessage.setText(finalWarning);
                    adapter.submit(new ArrayList<>());
                } else {
                    tvMessage.setVisibility(View.GONE);
                    tvSource.setText(finalSource);
                    adapter.submit(finalResult);
                }
            });
        });
    }

    private void onRecipeCooked(Recipe recipe) {
        String[] ingredients = recipe.uses.split(",");
        List<String> foundNames = new ArrayList<>();
        List<Long> foundIds = new ArrayList<>();

        for (String ingredient : ingredients) {
            String trimmed = ingredient.trim();
            if (trimmed.isEmpty()) continue;
            PantryItem item = db.findActiveByName(trimmed);
            if (item != null) {
                foundNames.add(item.name);
                foundIds.add(item.id);
            }
        }

        if (foundNames.isEmpty()) {
            StreakHelper.recordCooked(this, 0);
            Toast.makeText(this, " Great cooking! Recipe completed.", Toast.LENGTH_SHORT).show();
            return;
        }

        String[] nameArray = foundNames.toArray(new String[0]);
        boolean[] checked = new boolean[nameArray.length];
        for (int i = 0; i < checked.length; i++) checked[i] = true;

        new MaterialAlertDialogBuilder(this)
                .setTitle("Mark ingredients as used?")
                .setMultiChoiceItems(nameArray, checked, (dialog, which, isChecked) -> checked[which] = isChecked)
                .setPositiveButton("Done cooking!", (dialog, which) -> {
                    int markedCount = 0;
                    for (int i = 0; i < checked.length; i++) {
                        if (checked[i]) {
                            db.setStatus(foundIds.get(i), PantryItem.USED);
                            markedCount++;
                        }
                    }

                    if (markedCount == 0) {
                        Toast.makeText(this, "No ingredients marked.", Toast.LENGTH_SHORT).show();
                        return;
                    }

                    int streak = StreakHelper.recordCooked(this, markedCount);
                    String msg = (streak == 1)
                            ? " 1 item saved this week! Keep going!"
                            : " " + streak + " items saved this week! Great streak!";
                    Toast.makeText(this, msg, Toast.LENGTH_LONG).show();
                })
                .setNegativeButton("Cancel", null)
                .show();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        executor.shutdownNow();
    }
}